version: '3.3'

services:
  web:
    build: ./marketplace
    entrypoint: /usr/src/app/web-entrypoint.sh
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./marketplace/marketplace/.env
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./marketplace/marketplace/.env.db
  broker:
    image: redis
    restart: always
    ports:
      - 6379:6379
  celery:
    build: ./marketplace
    entrypoint: /usr/src/app/celery-entrypoint.sh
    depends_on:
      - db
      - broker
      - web
  nginx:
    build: ./nginx
    ports:
      - 8000:80
      - 443:443
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
      - db
# If SSL certificate is needed comment out the code below
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    depends_on:
#      - nginx
#    command: certonly --webroot -w /var/www/certbot --force-renewal --email snowtrueman.python@gmail.com -d german.anufrikov.com --agree-tos

volumes:
  postgres_volume:
  static_volume:
  media_volume: