# Generated by Django 4.1.4 on 2023-04-15 20:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_phone', models.CharField(max_length=16, verbose_name='Общий номер телефона')),
                ('general_email', models.CharField(max_length=50, verbose_name='Общий email')),
                ('general_address', models.TextField(verbose_name='Общий адрес')),
                ('facebook_url', models.TextField(max_length=50, verbose_name='Страница в Facebook')),
                ('twitter_url', models.TextField(max_length=50, verbose_name='Страница в Twitter')),
                ('linkedin_url', models.TextField(max_length=50, verbose_name='Страница в LinkedIn')),
                ('pinterest_url', models.TextField(max_length=50, verbose_name='Страница в Pinterest')),
                ('product_cache_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31536000)], verbose_name='Время кеширования карточки товара (с)')),
                ('ordinary_delivery_price', models.IntegerField(verbose_name='Стоимость обычной доставки')),
                ('express_delivery_price', models.IntegerField(verbose_name='Стоимость экспресс-доставки')),
                ('delivery_sum_to_free', models.IntegerField(verbose_name='Порог бесплатной доставки')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Guest', 'Guest')], default='User', max_length=5, verbose_name='Роль пользователя')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('orders', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заказы')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars', verbose_name='Аватар')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователя',
            },
        ),
    ]
