# Generated by Django 4.1.4 on 2023-04-15 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery_type', models.CharField(max_length=50, verbose_name='Тип доставки')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость доставки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость заказа')),
                ('payment_status', models.CharField(blank=True, choices=[('OK', 'Оплата прошла успешно.'), ('invalid_number', 'Указанный номер карты недействителен.'), ('card_expired', 'Срок действия карты истёк.'), ('insufficient funds', 'На карте недостаточно средств.'), ('processing_error', 'Ошибка на стороне платёжной системы.'), ('security_check_fail', 'Не удалось провести безопасную транзакцию.')], max_length=20, null=True, verbose_name='Статус оплаты')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('status', models.CharField(choices=[('created', 'Не оплачен'), ('paid', 'Оплачен'), ('delivery', 'В доставке'), ('success', 'Завершен'), ('canceled', 'Отменен')], default='created', max_length=8, verbose_name='Статус заказа')),
                ('comments', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета')], max_length=50, verbose_name='Способ оплаты')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_with_product', to='app_goods.goods', verbose_name='Товар')),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='app_orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товары в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_orders.payment', verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Позьзователь'),
        ),
    ]
